### ISSUE TITLE
M5stickc plus 2. Reboots when pasting a copied file

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#190]
When I try to copy and  paste a .ir file on another folder Bruce reboots without transferring the file.

**Comment by Ademolght** [comment]
me too with the cardputer

**Comment by bmorcelli** [comment]
This problem is related to the size of the buffer here https://github.com/pr3y/Bruce/blob/d05b1c05e28c6c049a2d8872e2dba74220d22e8b/src/core/sd_functions.cpp#L137 and here https://github.com/pr3y/Bruce/blob/d05b1c05e28c6c049a2d8872e2dba74220d22e8b/src/core/sd_functions.cpp#L212

Maybe using this global buffer https://github.com/pr3y/Bruce/blob/d05b1c05e28c6c049a2d8872e2dba74220d22e8b/src/core/globals.h#L94 can solve the pr

**Comment by Z-SHOCK-E** [comment]
Ok Thanks.

**Comment by bmorcelli** [comment]
Fixed here https://github.com/pr3y/Bruce/pull/194
