### ISSUE TITLE
CC1101 and NRF24L01 in one

### ISSUE THREAD

**Issue by M1cr0K1ller** [BruceDevices/firmware#288]
My question is it possible to attach here a NRF24L01 
![image](https://github.com/user-attachments/assets/83ff2c63-363e-4fe8-b8e3-732bbfae4439)
With 2 switches on MOSI and MISO that will eighter go to CC1101 or NRF24L01.
If it's possible, could some one do the schematic, cause i don't know how to do it right

**Comment by bisaw37** [comment]
Yes you totally can, and I’m planning to do something similar, but much simpler. Instead of 2 switches, just plug everything in together, and put one switch between the VCC of both of them. Only 1 switch to fumble around with, and it’s also scaleable. I’m going to do this with the cc1101, nrf24l01, pn533, and m5stack IR module.

**Comment by M1cr0K1ller** [comment]
That's actually a lot smarter. Thanks a lot!
