### ISSUE TITLE
Bug with WebUI

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#292]
WebUI works terribly, the site doesn't even start

**Comment by bmorcelli** [comment]
You know... Complaining won't make it work better, and won't make it any easy to find the bug you're trying to describe..

We can make a call and I'll show it working flawlessly, because probably you don't know how to use, or didn't even read anything about it.


You are using a Microcontroller, not a fullly server..

Next time you open an issu, make sure to folow the steps and write the things following the Template..

Thank you for your attention, it'll be closed now
