### ISSUE TITLE
Add RAW support with cc1101

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#362]
Cathack has had this for a long time, but Bruce (the best firmware) does not

**Comment by Petitoursbr1** [comment]
Yeah I also think it would be great 👍but it may be hard to implement so idk if it's going to be added....

**Comment by Asmodeux2** [comment]
Админ, не ожидал тебя увидеть на GitHub.

**Comment by bmorcelli** [comment]
It will come, in time

**Comment by Teapot321** [comment]
> Это придет, со временем
Add it faster pls

**Comment by Teapot174** [comment]
> Это придет, со временем

Add it soon, pls

**Comment by IncursioHack** [comment]
Duplicated:
https://github.com/pr3y/Bruce/issues/216
https://github.com/pr3y/Bruce/pull/248

**Comment by Petitoursbr1** [comment]
Just a question, what makes raw RF recording hard/slow to implement on Bruce ?

**Comment by bmorcelli** [comment]
Time and priorities..

**Comment by IncursioHack** [comment]
> Just a question, what makes raw RF recording hard/slow to implement on Bruce ?

Each implementation requires a number of tests, in addition, to make it work on various devices that we already have today (CC1101, RF433, FS1000...) and on various boards (Stick, Cardputer, ESP32-S3, Core, CYD, Lilygo... .). Another point is to do it in a way that does not impact other parts of the code.
Finally, there are priorities as @bmorcelli  mentioned.

Unfortunately, we dedicate ourselves to Bruce in the free moments we have and manage, we do not have the financial return to dedicate ourselves 100% to the project.

We invite you and everyone to develop for Bruce so that this process can be a little faster. Without this, unfortunately we are unable to carry out any implementation and/or changes in a timely manner.

**Comment by Petitoursbr1** [comment]
I totally get that you can’t go all-in on this project since it’s not your main job, but honestly, what you’re doing already is awesome, and I’m extremely grateful. I have a very limited knowledge when it comes to programming c++ so my help is just gonna be very limited for now...

**Comment by eadmaster** [comment]
For the **recording/receiving side**, getting a decoded dump of a signal if actually better than a raw dump, because the noise is filtered and so it is more reliable to replay.
