### ISSUE TITLE
Brucegotchi useful improvements

### ISSUE THREAD

**Issue by Sonys9** [BruceDevices/firmware#374]
1. When extracting a handshake, make an inscription on the screen somewhere with text like "Catching: TP-Link-1242", and if you only have access to the mac address, do a wi-Fi scan every 5 minutes in order to get a list like [{"name": "TP-Link-1242", "mac": "12:56:C3:61:C7:91"}, ...]
2. Please fix accidental crashes during handshake mining (the screen goes out completely)
3. When saving the handshake in the file name make not random characters, make the network name or mac address
4. Give the opportunity to set up the time of the handshake extraction (waiting for the client to connect) and the time of the deauth attack
5. Its catches broken handshakes very often (fix it please)

**Comment by bmorcelli** [comment]
1 and 3: the Sniffer captures packets, analyses them and takes action over some conditions.. making a wifi search takes time, that affects the sniffer, and the sniffer itself is capable of identify Mac Address (and maybe the SSID) of the beacon.. the files are saved not with random names, but the MAC address of the Access points..


5: as I mentioned before, it sniffs the packets, sometimes it can't catch all 3 or 4 packets of the EAPOL Handshake, and it is ok.. because it will wait until other device to connect and capture this handshake... Again, handshakes are exchanged during connection/reconnection.. this is something that Brucegotchi does, for 10seconds after changing channel, but it keeps only ~40s per channel

2: sniff packets uses lots of resources from the ESP32.. crashes are not desired, but understandably expected, and I personally haven't seen it happen..

4: I don't think it would be useful at all.. it would be better to enhance the RawSniffer with deauth and station deauth than add more complexity to something that should run on automatic, like a Pwnagotchi..
