### ISSUE TITLE
Key Copier for Physical Keys

### ISSUE THREAD

**Issue by AlvaroBagnara** [BruceDevices/firmware#479]
the same as what already exists in FlipperZero, a key image generator, something like ".key" files to see existing ones and also create new ones

![image](https://github.com/user-attachments/assets/6f4fb6bb-a70f-4e10-bce6-299b468fdd79)

**Comment by IncursioHack** [comment]
We have already raised this idea, although it is fun, it is difficult to apply to everything, another point that is complicated is that Bruce is adapted for various devices with screens of different sizes and pixels, and keeping the size of the key image standardized in screen would be a lot of work. I believe it should not be applied. For Flipper it makes sense because it will always be a single screen with the same size.
