### ISSUE TITLE
Bugs in Bruce e179ed3

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#508]
I want to report bugs in Bruce e179ed3.

1. The main function starts with Files, not WiFi.
2. Artifacts of the frame and battery icon at startup.
3. Unnecessary notification that this device does not support GIF when displaying intro
4. When entering an empty LittleFS, it crashes.
5. There are two sections with files, the first in others, the second in Files. I think you can remove sections with files from Others

**Comment by eadmaster** [comment]
> 1. The main function starts with Files, not WiFi

> There are two sections with files, the first in others, the second in Files. I think you can remove sections with files from Others

related: https://github.com/pr3y/Bruce/pull/500#issuecomment-2508949598

You can disable the "Files" menu if you want, currently reordering is not supported.

I think having some redundant menu entries can be useful. E.g. if you want hide the "Files" top-level menu without losing access to a basic functionality like the file manager.

> 3. Unnecessary notification that this device does not support GIF when displaying intro

Just rename `boot.gif` to `boot.gif.no`, this may be fixed in the future.

> 2. Artifacts of the frame and battery icon at startup.

On which device are you testing?

**Comment by Teapot174** [comment]
> On which device are you testing?

T-Embed cc1101


> You can disable the "Files" menu if you want, currently reordering is not supported.

I think in this case it is better to delete this menu altogether

**Comment by eadmaster** [comment]
> I think in this case it is better to delete this menu altogether

Since i use the file manager a lot,
I'd like to have a shortcut that is quicker to reach than "Other->Sd Card".... 

As alternative, with a menu reordering feature i could set "Others" as the 1st menu. (Same thing with the WebUI). 

> 4. When entering an empty LittleFS, it crashes.

this Didn't happen on my new T-Embed cc1101, which app/feature were you using?
