### ISSUE TITLE
Cc1101

### ISSUE THREAD

**Issue by chelick5** [BruceDevices/firmware#578]
how to solve the problem that the cc1101 module does not work when connected and the module selection menu freezes? I apologize for bothering you a second time, I just don’t understand what needs to be done to get the module to work.

**Comment by bmorcelli** [comment]
https://youtu.be/RVQrfghGVqw?si=4nw9nrrikceI3JiC

Push the wires into the grove connectors (push the wires into the dupont plastic)

You can take the dupont connector out, press the metal parts to tighten up the hole, making the connection better.. you can isolate the metal parts and use like this, or put the plastic back on..

The grove pins are thicker than Male Dupont connectors, so the problem you are facing is due to false contact...

![IMG_20241218_191820154.jpg](https://github.com/user-attachments/assets/c2474585-a13b-4da7-8cf0-06dca16f0ccd)

![IMG_20241218_191841986.jpg](https://github.com/user-attachments/assets/f6c5d084-8eac-4ad4-b46c-0e685931af7b)

![IMG_20241218_191803090.jpg](https://github.com/user-attachments/assets/12aadaac-b2d5-4c55-b890-2a4fb041c770)

Good luck.

**Comment by M5stick-c-plus2-guy** [comment]
Wich Part Is the terminal?
