### ISSUE TITLE
Connecting rfid and other stuff

### ISSUE THREAD

**Issue by Kcual** [BruceDevices/firmware#62]
Hello everyone, please tell me how to connect RFID-RC522 to M5Stick CPlus1.1. Also I would like to know about connecting FS1000A and card reader, is it possible to make it all work together (Rfid, FS1000A transmitter and card reader)? Does anyone have connection diagrams?

**Comment by Niximkk** [comment]
It is possible to use all of them together, but it's not that simple. Since the RFID module uses the Grove port, you won't need any modifications. Now, for the SD card and FS1000A transmitter, you can try using a protoboard, some female pins, and software changes, since you will need to use one at a time.
--- 

The FS1000A transmitter is plug and play, GND 5V G26.

<img src="https://github.com/user-attachments/assets/db3ae3db-cacd-437c-ab37-56964be2a0db" width="300" alt="Image description">

For the sd card, follow this:

| M5StickC | SD   |
|----------|------|
| 3V3      | 3V3  |
| GND      | GND  |
| 0        | CLK  |
| 36       | MISO |
| 26       | MOSI |
| GND      | CS   |

Now for the RFID module, the only one supported afaik is the [Official M5Stack one](https://shop.m5stack.com/products/rfid-unit-2-ws1850s). Which uses the grove port (i don't think you need a tutorial for that). 

## I hope this helps :3

**Comment by Kcual** [comment]
Thanks a lot

**Comment by Kcual** [comment]
Thanks a lot
